name: ServerJumpSK
version: 0.2.1
author: Nikd0
main: ga.nikd0.ServerJumpSK.ServerJumpSK
api-version: 1.13
depend: [Skript]
website: "https://github.com/Zettovec/ServerJumpSK"
description: "Send players across your BungeeCord network!"
commands:
  serverjumpsk:
    description: Basic command for admins. Can be turned off in the config.
    usage: /<command>
    aliases: [sjsk]
permissions:
  serverjumpsk.admin:
    description: Allows a player to use the /serverjumpsk (/sjsk) command.